### PR TITLE
added Beamdog Locale ID

### PR DESCRIPTION
**Pull request by ALIENQuake**

### CODE REVIEW

**Comment by FredrikLindgren** [comment]
This also needs amended documentation.

**Comment by ALIENQuake** [comment]
@FredrikLindgren How I can easy edit those tex files? It's completely unreadable with all those 'anchors' Why documentation can't simply use wiki or even markdown?

**Comment by FredrikLindgren** [comment]
I don't know, reading LaTeX is a skill like any other, I guess. I've already updated the documentation; see c4394e9ab73b44287d7ee2e6828b26dbcdd10eb7.

So I guess that's one more vote for rewriting the documentation.

**Comment by ALIENQuake** [comment]
That was fast. Definitely count my vote, documentation format is anything like I've seen so far. I guess it's the reason why weidu documentation have such bad state without modern code examples/best practices/what to not do etc. Please choose standard, easy to use system, which other modding framework/open source project use.

**Pull request merged**
