### PR TITLE
fix missing separator and invalid cut option

### PR DESCRIPTION
**Pull request by CrevsDaak**
Stuff I had to change on the Makefile to get it to work. The missing indentation was causing an error that stopped the compilation altogether, and cut was complaining about -z being passed to it so I removed that as well (I don't know of any version of the tool that takes -z as an argument, so I simply removed it. Still unsure if that was the right call).

### CODE REVIEW

**Comment by FredrikLindgren** [comment]
-z is an option for GNU cut, but the second cut strips the effects it has on the first invocation. @ALIENQuake, do you need null-terminated strings for this metadata thing, or was there some other reason for the -z option?

**Comment by ALIENQuake** [comment]
@FredrikLindgren I construct this command via examples + experimentation. Quick test using Windows + Cygwin shows that removal of the `-z` switch didn't change anything.

But the strange thing happen: suddenly this code:

> VERSION_MINOR := $(shell grep 'version =' src/version.ml | cut -d'"' -f2 | cut -c4-)

give me `.00` instead of `00`, it was working fine before. Fix is:

> VERSION_MINOR := $(shell grep 'version =' src/version.ml | cut -d'"' -f2 | cut -c**5**-)

@CrevsDaak Care to update PR?

**Comment by CrevsDaak** [comment]
Done. I had no idea GNU cut had -z as an option.

**Comment by ALIENQuake** [comment]
@FredrikLindgren Hi, please simply test those changes at you env and if it produce windows exe with correct 'version properties', then everything seems to be fine and you cna accept this PR. Don't let this minor thing be in limbo state indefinitely.

**Comment by FredrikLindgren** [comment]
Fixed in ee09a9e9a727f0f4a058d1644d72c8c1cd64b463.

Please write good commit messages. A year from now, or whenever, I would like to be able to tell what the commit was about (at a reasonable level of detail) without having to read the diff.

@ALIENQuake I don't see how grep could be returning that period unless it was coming from version.ml. Please verify your local copy.

**Pull request closed without merging**
