### PR TITLE
drawbacks of using ACTION_READLN

### PR DESCRIPTION
**Pull request by ALIENQuake**
redrafting to
```
Modders are urged to be considerate and use alternatives, notably a
SUBCOMPOENENT/FORCED_SUBCOMPOENENT or configuration files if they are suitable.
```

### CODE REVIEW

**Comment by mike1072** [comment]
> installation will be paused

This information is already included in the readme.

> impossible to save user choices, every new installation will require to repeat providing manual input

You can pipe input to WeiDU, so it is possible to re-use choices and they don't have to be entered manually.

> choices are not included inside weidu installation log, debug information is lost

The tutorial already mentions that READLN input isn't included in the weidu.log file.

> impossible to use weidu GROUP, LABEL and other features

You shouldn't expect those features to apply to anything other than components.

> impossible to display ACTION_READLN choices inside ~~GUI Tools~~ mod managers

That depends on how the mod is using READLN.

> Instead of ACTION_READLN please use SUBCOMPONENT feature.

External configuration files (e.g. .ini files) are better suited to handle the same needs.

**Comment by ALIENQuake** [comment]
@mike1072 While feedback is always welcomed, can't get the feeling that you 'missed' all of what has been told here: https://www.gibberlings3.net/forums/topic/29708-mod-action_readln-removal-brainstorming/?tab=comments#comment-263535
To recap: many mods/mod authors already get rid of READLN in order to not block installation, it can't pipe input because there is no way to detect which component is processed in advance, SUBCOMPONENT feature is the same amount of work for modders and the debug data is not lost as in case of config files. Finally, its' not about what is missing from the docs but how it was presented to the modders.
I will make adjustments and update this PR soon.

**Comment by ALIENQuake** [comment]
@FredrikLindgren This PR is now redrafted to:
```
Modders are urged to be considerate and use alternatives, notably a
SUBCOMPOENENT/FORCED_SUBCOMPOENENT or configuration files if they are suitable.
```

**Comment by FredrikLindgren** [comment]
I think that perhaps someone who is not already familiar with the problem will have difficulties understanding the problem when it is presented like that. I'll get back to you with a counter-offer.

**Comment by FredrikLindgren** [comment]
Sorry about forgetting this once again. I hope this can be resolved with 53c7dbf60544f1e9fdc23bd368a4d3023162cce1. I believe it hews fairly close to what you have written.

**Comment by ALIENQuake** [comment]
@FredrikLindgren It's perfect, thank you!

**Pull request closed without merging**
