### PR TITLE
Add documentation for ADD_STORE_ITEM_EX and related functions

### PR DESCRIPTION
**Pull request by Argent77**
Better late than never. This PR adds proper documentation for [this set of store-related functions](https://github.com/WeiDUorg/weidu/blob/master/src/tph/include/store_functions.tpa).

### CODE REVIEW

**Comment by 4Luke4** [comment]
@Argent77 

`ADD_STORE_ITEM_EX`: it seems `overwrite` does nothing...? I'm having the same issue with [ADD_STORE_ITEM](https://github.com/WeiDUorg/weidu/issues/174).
```
COPY_EXISTING "RIBALD.sto" "override"
	LPF "ADD_STORE_ITEM_EX"
	INT_VAR
		"stack" = 0
		"unlimited" = 1
		"overwrite" = 1
	STR_VAR
		"item_name" = "AX1H01"
		"position" = "LAST"
	END
	//ADD_STORE_ITEM + ~AX1H01~ LAST #0 #0 #0 ~identified~ #1 ~unlimited~
BUT_ONLY
```

**Comment by Argent77** [comment]
My assumption was that the `position` parameter affects only new item additions. Existing items are kept in place, but their content is updated if the `overwrite` parameter is set.

For relocating items you can use `REMOVE_STORE_ITEM_EX` to remove the original entry followed by `ADD_STORE_ITEM_EX` to add a new entry at the desired position.

**Comment by 4Luke4** [comment]
I see, thanks for clarifying.

Guess the same holds for `ADD_STORE_ITEM` then...

**Comment by Argent77** [comment]
@FredrikLindgren would it make sense to place the function descriptions in their own subsection?

**Comment by FredrikLindgren** [comment]
@Argent77 Thanks. Do you think you could squash the fix commits? Feel free to put the descriptions in a subsection.

**Comment by Argent77** [comment]
Commits are squashed.

For some reason I can't manage to register the subsection in the table of contents on my test system. Could you please add a subsection to the functions? I thought of `Store-related functions` or something like that.

**Comment by FredrikLindgren** [comment]
Done. Thanks.

**Pull request merged**
