### PR TITLE
load: load both gemrb paths

### PR DESCRIPTION
**Pull request by lynxlynxlynx**
fix the remainder of #153

This should do it, but I haven't tested. Conceptually it's fine, but I don't know if you treat paths on windows specially or anything like that (in my experience slashes work there too).

### CODE REVIEW

**Comment by lynxlynxlynx** [comment]
Or if you prefer a cleaner, but longer solution, it looks like the Filename module has everything:
https://ocaml.org/releases/4.10/htmlman/libref/Filename.html

**Comment by lynxlynxlynx** [comment]
@FredrikLindgren any preference, other feedback?

I was also not sure if the order is preserved — "shared" should be searched after the specified path.

**Comment by FredrikLindgren** [comment]
Sorry, I've been a bit preoccupied. The order is fine. Override will be loaded before gemrb_path, which will be loaded before shared.

Implemented in c1e885d683731632e51df2a3c0b6bd89f64682ac. Sorry for taking so long on this.

**Comment by lynxlynxlynx** [comment]
Don't worry about it, thanks! Can confirm it works as expected. What are your plans for the next release, time-wise?

**Comment by FredrikLindgren** [comment]
I can offer no time estimate. Development has been fairly dormant lately, and while things have mostly cleared up, now there's a fair backlog of features and bugs I feel I need to sort through.

**Pull request closed without merging**
